name: Build & Publish Docker

on:
  repository_dispatch:
    types: [docker-build]

permissions:
  contents: read # für Checkout
  packages: write # für Push in GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Extract version
        run: echo "VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v${{ env.VERSION }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          OWNER_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/$OWNER_NAME/$REPO_NAME:${{ env.VERSION }}
          echo "Building image: $IMAGE"
          docker build -t $IMAGE .

      - name: Push Docker image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          OWNER_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/$OWNER_NAME/$REPO_NAME:${{ env.VERSION }}
          echo "Pushing image: $IMAGE"
          docker push $IMAGE
